services:
  - type: web
    name: encore-web
    env: python
    rootDir: encore
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120 --graceful-timeout 120 --keep-alive 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: FIELD_ENCRYPTION_KEY
        sync: false

  - type: worker
    name: encore-celery
    env: python
    rootDir: encore
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker -l info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: FIELD_ENCRYPTION_KEY
        sync: false
