# Generated by Django 5.2.11 on 2026-02-11 16:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_Playlist_id', models.CharField(blank=True, help_text='YouTube Playlist ID (e.g. PL...) - unique per user', max_length=100, null=True)),
                ('spotify_Playlist_id', models.CharField(blank=True, help_text='Spotify Playlist ID once created', max_length=100, null=True)),
                ('spotify_Playlist_uri', models.CharField(blank=True, help_text='spotify:Playlist:... URI', max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('syncing', 'Syncing'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('success', 'Success')], default='idle', max_length=20)),
                ('source_status', models.CharField(choices=[('active', 'Active'), ('unavailable', 'Unavailable'), ('deleted', 'Deleted'), ('private', 'Private')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('position', models.PositiveIntegerField(help_text='Original position in YouTube Playlist', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_removed_from_source', models.BooleanField(default=False, help_text='True if video 404s or is private on YouTube')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'youtube_Playlist_id'], name='playlists_p_user_id_ac0721_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'spotify_Playlist_id'], name='playlists_p_user_id_4aba63_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('youtube_Playlist_id__isnull', False)), fields=('user', 'youtube_Playlist_id'), name='unique_youtube_per_user'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['Playlist', 'youtube_video_id'], name='playlists_p_Playlis_6dec62_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['Playlist', 'position'], name='playlists_p_Playlis_5d16e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('Playlist', 'youtube_video_id')},
        ),
    ]
