# Generated by Django 5.2.11 on 2026-02-18 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_playlist_id', models.CharField(blank=True, help_text='YouTube playlist ID (e.g. PL...) - unique per user', max_length=100, null=True)),
                ('spotify_playlist_id', models.CharField(blank=True, help_text='Spotify playlist ID once created', max_length=100, null=True)),
                ('spotify_playlist_uri', models.CharField(blank=True, help_text='spotify:playlist:... URI', max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('syncing', 'Syncing'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('success', 'Success')], default='idle', max_length=20)),
                ('source_status', models.CharField(choices=[('active', 'Active'), ('unavailable', 'Unavailable'), ('deleted', 'Deleted'), ('private', 'Private')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('position', models.PositiveIntegerField(help_text='Original position in YouTube playlist', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_removed_from_source', models.BooleanField(default=False, help_text='True if video 404s or is private on YouTube')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, help_text='Dict of {playlist_item_id: error_reason} or general errors', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('user', 'Manual User Trigger'), ('cron', 'Scheduled Re-sync'), ('retry', 'Retry After Failure')], default='user', max_length=50)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='playlists.playlist')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=50)),
                ('spotify_track_uri', models.CharField(max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.0, help_text='0.0000 to 1.0000 - higher = better match', max_digits=5)),
                ('match_method', models.CharField(choices=[('auto_fuzzy', 'Auto Fuzzy Matching'), ('exact_id', 'Exact YouTube ID in description/metadata'), ('manual', 'User Manual Override')], default='auto_fuzzy', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='True if this is the currently selected best match')),
                ('match_metadata', models.JSONField(blank=True, help_text='Snapshot of Spotify API response (artist, album, duration, etc.)', null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='playlists.playlistitem')),
            ],
            options={
                'ordering': ['-confidence_score', '-matched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'youtube_playlist_id'], name='playlists_p_user_id_2fbdb7_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'spotify_playlist_id'], name='playlists_p_user_id_7c3cb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('youtube_playlist_id__isnull', False)), fields=('user', 'youtube_playlist_id'), name='unique_youtube_per_user'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'youtube_video_id'], name='playlists_p_playlis_9cfecf_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'position'], name='playlists_p_playlis_84fb2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'youtube_video_id')},
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['playlist', 'status'], name='playlists_s_playlis_a3adfb_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['started_at'], name='playlists_s_started_819e08_idx'),
        ),
        migrations.AddIndex(
            model_name='trackmatch',
            index=models.Index(fields=['playlist_item', 'is_active'], name='playlists_t_playlis_c1661b_idx'),
        ),
        migrations.AddIndex(
            model_name='trackmatch',
            index=models.Index(fields=['spotify_track_id'], name='playlists_t_spotify_d4aae1_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('playlist_item', 'is_active'), name='unique_active_match_per_item'),
        ),
    ]
