# Generated by Django 5.2.11 on 2026-02-11 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotify_playlist_id',
            field=models.CharField(blank=True, help_text='Spotify playlist ID once created', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotify_playlist_uri',
            field=models.CharField(blank=True, help_text='spotify:playlist:... URI', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, help_text='YouTube playlist ID (e.g. PL...) - unique per user', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='position',
            field=models.PositiveIntegerField(help_text='Original position in YouTube playlist', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, help_text='Dict of {playlist_item_id: error_reason} or general errors', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('user', 'Manual User Trigger'), ('cron', 'Scheduled Re-sync'), ('retry', 'Retry After Failure')], default='user', max_length=50)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='playlists.playlist')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['playlist', 'status'], name='playlists_s_playlis_a3adfb_idx'), models.Index(fields=['started_at'], name='playlists_s_started_819e08_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=50)),
                ('spotify_track_uri', models.CharField(max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.0, help_text='0.0000 to 1.0000 - higher = better match', max_digits=5)),
                ('match_method', models.CharField(choices=[('auto_fuzzy', 'Auto Fuzzy Matching'), ('exact_id', 'Exact YouTube ID in description/metadata'), ('manual', 'User Manual Override')], default='auto_fuzzy', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='True if this is the currently selected best match')),
                ('match_metadata', models.JSONField(blank=True, help_text='Snapshot of Spotify API response (artist, album, duration, etc.)', null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='playlists.playlistitem')),
            ],
            options={
                'ordering': ['-confidence_score', '-matched_at'],
                'indexes': [models.Index(fields=['playlist_item', 'is_active'], name='playlists_t_playlis_c1661b_idx'), models.Index(fields=['spotify_track_id'], name='playlists_t_spotify_d4aae1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('playlist_item', 'is_active'), name='unique_active_match_per_item')],
            },
        ),
    ]
