# Generated by Django 5.2.11 on 2026-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_channel_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_item_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_privacy_status',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
