# Generated by Django 5.2.11 on 2026-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_youtube_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='sync_mode',
            field=models.CharField(choices=[('append_only', 'Append Only (add missing, never remove)'), ('smart_diff', 'Smart Diff (add/remove based on source, preserve manual changes)'), ('full_replace', 'Full Replace (mirror source exactly – destructive)')], default='smart_diff', help_text='How to handle re-syncs', max_length=20),
        ),
    ]
