# Generated by Django 5.2.11 on 2026-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_sync_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncoperation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='syncoperation',
            name='playlists_s_playlis_a3adfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncoperation',
            name='playlists_s_started_819e08_idx',
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('playlist', 'status'), name='unique_active_sync_per_playlist'),
        ),
    ]
